# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sensor_id', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('moisture', models.FloatField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
